### ISSUE TITLE
Error on Etherscan

### ISSUE THREAD

**Issue by jhubbardsf** [zdenham/diamond-etherscan#1]
Hey, I know this was just a small project for you but I was really interested in trying to get it implemented and maybe do some improvements. But I'm hitting a wall trying to test it out. I can create the dummy implementation. Attach the etherscan facet. All that, even in your example project. But when I actually go on etherscan and try to attach the proxy I get this issue

```
The proxy contract verification completed with the below message:

This contract does not look like it contains any delegatecall opcode sequence.
```

The Diamond I deployed is [here](https://rinkeby.etherscan.io/address/0xF91ff0d3F883d885E14dd9B8d31d1dCb3318A754#code).

Louper for the Diamond is [here](https://louper.dev/diamond/0xF91ff0d3F883d885E14dd9B8d31d1dCb3318A754?network=rinkeby)

The DummyDiamondImplement is [here](https://rinkeby.etherscan.io/address/0x962956885a86825Ee65F01dF7ceFc413436750ac#code).

It's when I go to the Diamond etherscan page and try to connect the proxy as 0x962956885a86825Ee65F01dF7ceFc413436750ac that I get that error. Do you see anything that I'm doing obviously wrong here? Or is it possible Etherscan updated how they handle proxies in the past few months?

**Comment by zdenham** [comment]
Hey @jhubbardsf apologies I must have missed this.

Did you end up figuring it out?

**Comment by jhubbardsf** [comment]
Yeah, got it working. Just needed not to change anything in the proxy that etherscan pointed it to initially.
