### ISSUE TITLE
About Implementing `implementation()`

### ISSUE THREAD

**Issue by mudgen** [zdenham/diamond-etherscan#2]
Hello,
Shouldn't the [DiamondEtherscanFacet.sol](https://github.com/zdenham/diamond-etherscan/blob/main/contracts/facets/DiamondEtherscanFacet.sol) facet implement the ` implementation()` function in order to implement EIP 1967?   Right now it implements the `dummyImplementation()` function.

**Comment by zdenham** [comment]
You are correct, the current implementation is non-compliant.

We should also issue an `Upgraded` event when the implementation is updated. I'll add these changes right now!

**Comment by zdenham** [comment]
Resolved here: https://github.com/zdenham/diamond-etherscan/pull/3

**Comment by mudgen** [comment]
Cool, thanks!
