### ISSUE TITLE
Function.prototype.apply was called on undefined, which is a undefined and not a function

### ISSUE THREAD

**Issue by 0xautohub** [zdenham/diamond-etherscan#4]
When I try to add function selectors by calling diamondCut() function on `louper.dev`, I have input this tuple data as the first argument 
`(0x2cb01a89b7c474b0fd0b7958dcda5077ab50227b0,1,[0x5c60da1b,0xc39aa07d])`
But I have faced this error (seems svelte.js input filed validation error)

![image](https://user-images.githubusercontent.com/5579669/208453841-8f014a65-3a94-4628-a1a6-251ee06734a8.png)

**Comment by 0xautohub** [comment]
Any advice, please

**Comment by zdenham** [comment]
Hi! I think this seems to be an issue with louper, not diamond-etherscan, are you using diamond-etherscan?

**Comment by 0xautohub** [comment]
> Hi! I think this seems to be an issue with louper, not diamond-etherscan, are you using diamond-etherscan?

Yeah, totally agree with you. I'm using diamond-etherscan now. really awesome
